#wait in seconds
long.wait=30
short.wait=10
text.wait=2

#base url
base.url=https://mymarket.ge/

#uselogin
login.mail=gio.mikeladze19990@gmail.com

#password
login.password=Giorguna2000!

#user ID
user.id=ID 9060160

#visiturl
visit.url=https://www.mymarket.ge/ka/pr-form/

#login
login.url=https://auth.tnet.ge/ka/user/login?Continue=https%3A%2F%2Fwww.mymarket.ge%2Fka%2F


#btn
sell.url=https://www.mymarket.ge/ka/pr-form?Org=0&PCat=0
buy.url=https://www.mymarket.ge/ka/pr-form?Org=1&PCat=0
rent.url=https://www.mymarket.ge/ka/pr-form?Org=2&PCat=2
service.url=https://www.mymarket.ge/ka/pr-form?Org=3&PCat=1


#API
BASE_URL=https://api.escuelajs.co/api/v1
DEF.TITLE=product
DEF.IMAGE=https://placehold.co/600x400
DEF.DESCRIPTION=test description
DEF.CATID=1
DEF.PRICE=10
UNIQ.TITLE=UNIQPRODUCT